import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import QRCode from'qrcode';
import{BrowserQRCodeReader}from'@zxing/browser';
import'./styles.css';

let currentOperator=sessionStorage.getItem('exc26_operator')||''; let authLost=()=>{};
const NAV=[['overview','Overview'],['prereg','Pre-Registration'],['events','Event Registration'],['profiles','Profiles'],['abstracts','Abstracts'],['brochure','Brochure'],['contact','Contact'],['gmail','QR Gmail'],['scanner','QR Scanner'],['admins','Admin Management'],['credentials','Admin Credentials']];
const EXPORT_ACTION={overview:'overview',prereg:'master_list',events:'event_list',profiles:'profiles',abstracts:'abstract_list',brochure:'brochure_info',contact:'site_content',gmail:'profiles',scanner:'qr_logs',admins:'admins',credentials:'admin_credentials'};
function csvValue(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function downloadPageData(page){const action=EXPORT_ACTION[page];if(!action)return;const j=await call(action);if(page==='brochure'){if(j.url)window.open(j.url,'_blank','noopener,noreferrer');return}const rows=j.data||j.events||j.counts||[];const list=Array.isArray(rows)?rows:(rows&&typeof rows==='object'?[rows]:[]);if(!list.length){downloadBlob(new Blob(['No records found.'],{type:'text/plain'}),page+'-export.txt');return}const keys=[...new Set(list.flatMap(x=>Object.keys(x||{})))];const csv=[keys.join(','),...list.map(x=>keys.map(k=>csvValue(x[k])).join(','))].join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`excelsior26-${page}-export.csv`)}
async function login(username){
 const r=await fetch('/api/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username})});
 const j=await r.json().catch(()=>({}));
 if(!r.ok||!j.ok)throw new Error(j.error||'Operator entry failed');
 currentOperator=j.admin.username;
 sessionStorage.setItem('exc26_operator',currentOperator);
 return j.admin;
}
function logout(){currentOperator='';sessionStorage.removeItem('exc26_operator');authLost()}

async function call(action,payload={}){
 const r=await fetch('/api/admin-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,username:currentOperator,...payload})});
 const j=await r.json().catch(()=>({}));
 if(!r.ok||!j.ok)throw new Error(j.error||'Admin request failed');
 return j;
}
function Console({admin}){const[page,setPage]=useState('overview');return <div className="app"><aside><div className="brand">EXCELSIOR<span>'26</span><small>ADMIN CONSOLE</small></div><nav>{NAV.map(x=><button className={page===x[0]?'active':''} onClick={()=>setPage(x[0])} key={x[0]}><b>{x[0].slice(0,1).toUpperCase()}</b>{x[1]}</button>)}</nav><div className="user"><strong>{admin.display_name||'Administrator'}</strong><small>{admin.email}</small></div></aside><main><header><div><small className="kicker">EXCELSIOR'26 / CONTROL CENTER</small><h2>{NAV.find(x=>x[0]===page)[1]}</h2></div><div className="header-actions"><button className="download-btn" onClick={()=>downloadPageData(page)}>⇩ Download</button>{page==='credentials'&&<button className="download-btn" onClick={async()=>{try{const r=await fetch('/api/admin-credentials-pdf',{headers:{Authorization:`Bearer ${adminToken}`}});if(!r.ok)throw new Error(await r.text());downloadBlob(await r.blob(),'EXCELSIOR26_Admin_Credentials.pdf')}catch(e){alert(e.message)}}}>⇩ Credentials PDF</button>}<button className="lock-btn" onClick={logout}>Lock</button><span className="online">● {admin.display_name||'Admin'}</span></div></header><div className="content"><Page page={page} admin={admin}/></div></main><div className="bottom">{NAV.slice(0,5).map(x=><button className={page===x[0]?'active':''} onClick={()=>setPage(x[0])} key={x[0]}>{x[1].split(' ')[0]}</button>)}</div></div>}

function Page({page,admin}){if(page==='overview')return <Overview/>;if(page==='prereg')return <Review title="Pre-Registration Review" action="master_review" fields={['master_id','full_name','email','phone','year','pre_payment_status','pre_utr','pre_registration_status','pre_approved_by','pre_approved_at']}/>;if(page==='events')return <Events/>;if(page==='profiles')return <Profiles/>;if(page==='abstracts')return <Abstracts/>;if(page==='brochure')return <Brochure/>;if(page==='contact')return <Contact/>;if(page==='gmail')return <Gmail/>;if(page==='scanner')return <Scanner/>;if(page==='credentials')return <Credentials admin={admin}/>;return <Admins admin={admin}/>}
function Overview(){const[d,setD]=useState(null),[e,setE]=useState('');
 useEffect(()=>{call('overview').then(setD).catch(x=>setE(x.message))},[]);
 if(e)return <Panel title="Overview"><Alert text={e}/></Panel>;
 const c=d?.counts||['—','—','—','—'];return <><div className="hero"><div><small className="kicker">COMMAND OVERVIEW</small><h1>Good to see you.</h1><p>Monitor registrations, payments, abstracts, event activity and participant communication from one workspace.</p></div><div className="hero-logo">E<span>'26</span></div></div><div className="stats">{[['Pre-registrations',c[0]],['Event registrations',c[1]],['Abstract submissions',c[2]],['QR verifications',c[3]]].map(x=><div className="stat" key={x[0]}><small>LIVE</small><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="cols"><Panel title="Operations"><Action title="Registration review" text="Approve or reject master registrations and event payments."/><Action title="Abstract desk" text="Review submissions with clear status and reviewer metadata."/><Action title="QR communication" text="Prepare, approve and send participant QR emails securely."/></Panel><Panel title="Security"><Row a="Access mode" b="Direct console"/><Row a="Admin records" b="admin_accounts"/><Row a="API operations" b="Vercel Functions"/><Row a="Service credentials" b="Server only"/></Panel></div></>
}

function Review({title,action,fields}){const[d,setD]=useState(null),[q,setQ]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');useEffect(()=>{call(action==='master_review'?'master_list':'event_list').then(x=>setD(x.data||[])).catch(x=>setError(x.message))},[action]);const list=useMemo(()=>{const a=d||[];return a.filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()))},[d,q]);async function act(id,status){setBusy(id+status);setError('');try{await call(action,{id,status});const x=await call(action==='master_review'?'master_list':'event_list');setD(x.data||[])}catch(e){setError(e.message)}finally{setBusy('')}}return <Panel title={title} extra={<span className="pill">{list.length} records</span>}>{error&&<Alert text={error}/>}<div className="toolbar"><input placeholder="Search records…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{fields.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{fields.map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td><button className="mini good" disabled={!!busy} onClick={()=>act(r.id,'approved')}>{busy===r.id+'approved'?'…':'Approve'}</button><button className="mini bad" disabled={!!busy} onClick={()=>act(r.id,'rejected')}>{busy===r.id+'rejected'?'…':'Reject'}</button></td></tr>)}</tbody></table></div>}</Panel>
}

function Events(){const[d,setD]=useState(null),[cfg,setCfg]=useState(null),[tab,setTab]=useState('registrations'),[q,setQ]=useState('');useEffect(()=>{Promise.all([call('event_list'),call('event_config')]).then(x=>{setD(x[0].data||[]);setCfg(x[1].data||[])}).catch(()=>{})},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <><Panel title="Event Registration" extra={<div className="tabs"><button className={tab==='registrations'?'sel':''} onClick={()=>setTab('registrations')}>Registrations</button><button className={tab==='config'?'sel':''} onClick={()=>setTab('config')}>Event configuration</button></div>}>{tab==='registrations'?<><div className="toolbar"><input placeholder="Search participant, event, UTR…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{['master_id','name','event','fee','utr','payment_status','status','team_id','event_code'].map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{list.map(r=><EventRow key={r.id} r={r} reload={()=>call('event_list').then(x=>setD(x.data||[]))}/>)}</tbody></table></div>}</>:<Config rows={cfg} setRows={setCfg}/>}</Panel></>
}
function EventRow({r,reload}){const[b,setB]=useState(false);async function act(kind,status){setB(true);try{await call(kind,{id:r.id,status});await reload()}catch(e){alert(e.message)}finally{setB(false)}}return <tr>{['master_id','name','event','fee','utr','payment_status','status','team_id','event_code'].map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td><button className="mini good" disabled={b} onClick={()=>act('payment_review','approved')}>Pay ✓</button><button className="mini good" disabled={b} onClick={()=>act('event_review','approved')}>Approve</button><button className="mini bad" disabled={b} onClick={()=>act('event_review','rejected')}>Reject</button></td></tr>}
function Config({rows,setRows}){return <div className="config-grid">{rows.map(x=><div className="config-card" key={x.key}><div className="editor-title"><b>{x.title}</b><span className="pill">{x.enabled?'Enabled':'Disabled'}</span></div><Field label="Title"><input value={x.title||''} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,title:e.target.value}:y))}/></Field><div className="two"><Field label="Fee"><input type="number" value={x.fee||0} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,fee:e.target.value}:y))}/></Field><Field label="Enabled"><select value={String(x.enabled)} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,enabled:e.target.value==='true'}:y))}><option value="true">Enabled</option><option value="false">Disabled</option></select></Field></div><button className="primary" onClick={async()=>{try{await call('event_config_update',x);alert('Event configuration saved.')}catch(e){alert(e.message)}}}>Save configuration</button></div>)}</div>}
function Profiles(){const[d,setD]=useState(null),[q,setQ]=useState('');useEffect(()=>{call('profiles').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <Panel title="Participant Profiles"><div className="toolbar"><input placeholder="Search master ID, name, email or phone…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<Table rows={list} fields={['master_id','full_name','email','phone','year','pre_payment_status','pre_registration_status','created_at']}/>}</Panel>}
function Abstracts(){const[d,setD]=useState(null),[q,setQ]=useState(''),[downloading,setDownloading]=useState('');useEffect(()=>{call('abstract_list').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));async function review(id,status){try{await call('abstract_review',{id,status});setD((await call('abstract_list')).data||[])}catch(e){alert(e.message)}}async function download(id){setDownloading(id);try{const x=await call('abstract_download',{id});if(!x.url)throw new Error('Secure download link was not returned.');window.open(x.url,'_blank','noopener,noreferrer')}catch(e){alert(e.message)}finally{setDownloading('')}}return <Panel title="Abstract Review"><div className="toolbar"><input placeholder="Search title, master ID or event…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{['master_id','event_title','title','status','submitted_at','file_name'].map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>File</th><th>Review</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{['master_id','event_title','title','status','submitted_at','file_name'].map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td>{r.file_path?<button className="mini" disabled={downloading===r.id} onClick={()=>download(r.id)}>{downloading===r.id?'Opening…':'Download PDF'}</button>:<span className="muted">No file</span>}</td><td><button className="mini good" onClick={()=>review(r.id,'approved')}>Approve</button><button className="mini bad" onClick={()=>review(r.id,'rejected')}>Reject</button><button className="mini" onClick={()=>review(r.id,'resubmission_required')}>Resubmit</button></td></tr>)}</tbody></table></div>}</Panel>}
function Brochure(){const[file,setFile]=useState(null),[busy,setBusy]=useState(false);return <Panel title="Brochure"><div className="buttons"><button onClick={async()=>{try{const x=await call('brochure_info');if(x.url)window.open(x.url,'_blank','noopener,noreferrer')}catch(e){alert(e.message)}}}>Download current brochure PDF</button></div><div className="info">Existing bucket: <b>excelsior-brochure</b>. It is public, PDF-only, with a 50 MB limit. Replacement is server-controlled.</div><Field label="Replace brochure PDF"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><button className="primary" disabled={!file||busy} onClick={async()=>{setBusy(true);try{const reader=new FileReader();reader.onload=async()=>{try{await call('brochure_upload',{name:file.name,data_url:String(reader.result)});alert('Brochure replaced successfully.')}catch(e){alert(e.message)}finally{setBusy(false)}};reader.readAsDataURL(file)}catch(e){setBusy(false);alert(e.message)}}}>{busy?'Uploading…':'Upload replacement'}</button></Panel>}
function Contact(){const[d,setD]=useState(null);useEffect(()=>{call('site_content').then(x=>setD((x.data||[]).filter(y=>['contact','contacts'].includes(String(y.key||'').toLowerCase())))).catch(()=>setD([]))},[]);if(!d)return <Panel title="Contact / Shared Site Content"><Loading/></Panel>;return <Panel title="Contact / Shared Site Content"><div className="info">This edits the shared <b>site_content</b> source used by the participant portal. No duplicate content store is created.</div>{d.map(x=><div className="editor" key={x.key}><div className="editor-title"><b>{x.title||x.key}</b><span className="pill">{x.enabled?'Published':'Disabled'}</span></div><Field label="Title"><input value={x.title} onChange={e=>setD(d.map(y=>y.key===x.key?{...y,title:e.target.value}:y))}/></Field><Field label="Content"><textarea rows="6" value={x.content} onChange={e=>setD(d.map(y=>y.key===x.key?{...y,content:e.target.value}:y))}/></Field><button className="primary" onClick={async()=>{try{await call('content_update',x);alert('Saved successfully.')}catch(e){alert(e.message)}}}>Save changes</button></div>)}</Panel>}
function Gmail(){const[d,setD]=useState(null),[sel,setSel]=useState([]),[subject,setSubject]=useState("EXCELSIOR'26 Registration QR"),[body,setBody]=useState("Hello {{name}}, your EXCELSIOR'26 registration QR is ready. Master ID: {{master_id}}."),[busy,setBusy]=useState(false),[qr,setQr]=useState('');useEffect(()=>{call('profiles').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const all=d&&d.length>0&&d.every(x=>sel.includes(x.id));const toggle=id=>setSel(s=>s.includes(id)?s.filter(x=>x!==id):s.concat(id));async function preview(){const x=(d||[]).find(y=>sel.includes(y.id));if(!x)return;const z=await call('qr_prepare',{master_ids:[x.id]});const item=z.data?.[0];if(item)setQr(await QRCode.toDataURL(JSON.stringify({master_id:item.master_id,token:item.qr.token}),{width:260}))}async function send(){setBusy(true);try{const z=await call('qr_prepare',{master_ids:sel});const recipients=(z.data||[]).map(x=>({master_id:x.master_id,email:x.email,qr_credential_id:x.qr.id}));const queued=await call('qr_queue',{recipients,subject,body_html:body});const sent=await fetch('/api/send-qr-email',{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({queue_ids:(queued.data||[]).map(x=>x.id)})});const sj=await sent.json();if(!sent.ok||!sj.ok)throw new Error(sj.error||'Send failed');alert('QR email processing complete.');setSel([])}catch(e){alert(e.message)}finally{setBusy(false)}}return <><Panel title="QR Gmail" extra={<span className="pill blue">{sel.length} selected</span>}><div className="info">Select recipients, edit the template, preview a QR, then send through the server. Credentials never enter browser code.</div><div className="toolbar"><button onClick={()=>setSel(all?[]:(d||[]).map(x=>x.id))}>{all?'Unselect All':'Select All'}</button><button onClick={()=>setSel([])}>Clear All</button></div>{!d?<Loading/>:<div className="recipients">{d.map(x=><label key={x.id}><input type="checkbox" checked={sel.includes(x.id)} onChange={()=>toggle(x.id)}/><span><b>{x.full_name}</b><small>{x.email} • {x.master_id}</small></span></label>)}</div>}</Panel><div className="cols"><Panel title="Email template"><Field label="Subject"><input value={subject} onChange={e=>setSubject(e.target.value)}/></Field><Field label="Body"><textarea rows="9" value={body} onChange={e=>setBody(e.target.value)}/></Field><small className="muted">Placeholders: {{name}}, {{master_id}}, {{email}}</small><div className="buttons"><button onClick={preview} disabled={!sel.length}>Preview QR</button><button className="primary" onClick={send} disabled={!sel.length||busy}>{busy?'Sending…':'Send selected'}</button></div></Panel><Panel title="QR preview">{qr?<img className="qr" src={qr}/>:<div className="preview">Select a participant and preview their QR.</div>}</Panel></div></>}
function Scanner(){const[t,setT]=useState(''),[r,setR]=useState(null),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),video=React.useRef(null),reader=React.useRef(null);useEffect(()=>()=>{try{reader.current?.reset()}catch{}},[]);async function validate(token=t){setBusy(true);try{setR(await call('qr_validate',{token}))}catch(e){setR({error:e.message})}finally{setBusy(false)}}async function start(){try{reader.current=new BrowserQRCodeReader();setRunning(true);await reader.current.decodeFromVideoDevice(undefined,video.current,async result=>{if(result){const text=result.getText();setT(text);await validate(text);reader.current?.reset();setRunning(false)}})}catch(e){setR({error:'Camera unavailable. Use manual token entry or allow camera access.'});setRunning(false)}}return <Panel title="QR Scanner"><div className="scanner live"><video ref={video} muted playsInline/><div className="scan-overlay">ALIGN QR INSIDE FRAME</div></div><div className="buttons"><button onClick={start} disabled={running}>{running?'Scanning…':'Start camera'}</button><button onClick={()=>{reader.current?.reset();setRunning(false)}}>Stop</button></div><Field label="Manual token"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Paste QR token"/></Field><button className="primary" disabled={!t||busy} onClick={()=>validate()}>{busy?'Validating…':'Validate token'}</button>{r&&<div className={'scan-result '+(r.result||'invalid')}><b>{r.result||'error'}</b><span>{r.reason||r.error}</span>{r.master_id&&<small>Master ID: {r.master_id}</small>}</div>}</Panel>}
function Credentials({admin}){const[d,setD]=useState(null);useEffect(()=>{call('admin_credentials').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);return <Panel title="Admin Credentials"><div className="info"><b>10 operator accounts</b>. Passwords are never sent to browser code. Owner can download the protected credential PDF when ADMIN_CREDENTIALS_JSON is configured in Vercel.</div>{!d?<Loading/>:<Table rows={d} fields={['username','display_name','role']}/>}<div className="buttons"><button className="primary" onClick={async()=>{try{const r=await fetch('/api/admin-credentials-pdf',{headers:{Authorization:`Bearer ${adminToken}`}});if(!r.ok)throw new Error(await r.text());downloadBlob(await r.blob(),'EXCELSIOR26_Admin_Credentials.pdf')}catch(e){alert(e.message)}}}>Download credential PDF</button><button onClick={()=>downloadPageData('credentials')}>Download user list CSV</button></div></Panel>}
function Admins({admin}){const[d,setD]=useState(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{call('admins').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);if(admin.role!=='owner')return <Panel title="Admin Management"><Alert text="Owner authorization is required for this area."/></Panel>;async function add(){setBusy(true);try{await call('admin_create',{email,display_name:name});alert('Admin record created.');setName('');setEmail('');setD((await call('admins')).data||[])}catch(e){alert(e.message)}finally{setBusy(false)}}return <Panel title="Admin Management"><div className="info">Owner-only. Maximum 10 enabled admins. Admin records are maintained directly here.</div><div className="form-row"><Field label="Display name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Gmail"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><button className="primary" disabled={!name||!email||busy} onClick={add}>{busy?'Adding…':'Add admin'}</button></div>{!d?<Loading/>:<Table rows={d} fields={['display_name','email','enabled','created_at']}/>}</Panel>}
function Table({rows,fields}){if(!rows?.length)return <div className="empty">No records found.</div>;const c=fields||Object.keys(rows[0]).slice(0,8);return <div className="table"><table><thead><tr>{c.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{c.map(x=><td key={x}>{String(r[x]??'—')}</td>)}</tr>)}</tbody></table></div>}
const Action=p=><div className="action"><b>{p.title}</b><span>{p.text}</span><i>→</i></div>;const Row=p=><div className="row"><b>{p.a}</b><span className="pill green">{p.b}</span></div>;const Panel=p=><section className="panel"><div className="panel-head"><h3>{p.title}</h3>{p.extra}</div>{p.children}</section>;const Field=p=><label className="field"><small>{p.label}</small>{p.children}</label>;const Alert=p=><div className="alert">{p.text}</div>;const Spin=()=> <div className="spin"/>;const Loading=()=> <div className="loading"><Spin/>Loading…</div>;

function LoginOverlay({onLogin}){const[u,setU]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const users=Array.from({length:10},(_,i)=>'exc26admin'+String(i+1).padStart(2,'0'));async function submit(e){e.preventDefault();setBusy(true);setError('');try{const a=await login(u);onLogin(a)}catch(x){setError(x.message)}finally{setBusy(false)}}return <div className="login-overlay"><div className="login-card"><div className="brand-mark">EXCELSIOR<span>'26</span></div><small className="kicker">OPERATOR ACTIVITY CONTROL</small><h1>Admin access</h1><p>Select the operator account entering the console. Every action is recorded.</p><form onSubmit={submit}><label className="field"><small>Operator</small><select value={u} onChange={e=>setU(e.target.value)}><option value="">Select operator</option>{users.map(x=><option key={x} value={x}>{x}</option>)}</select></label>{error&&<Alert text={error}/>}<button className="primary login-submit" disabled={!u||busy}>{busy?'Entering…':'Enter Admin Console'}</button></form></div></div>}
function App(){const[admin,setAdmin]=useState(null);useEffect(()=>{authLost=()=>setAdmin(null);if(currentOperator){login(currentOperator).then(setAdmin).catch(()=>setAdmin(null))}},[]);if(!admin)return <LoginOverlay onLogin={setAdmin}/>;return <Console admin={admin}/>}
createRoot(document.getElementById('root')).render(<App/>);
