import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import QRCode from'qrcode';
import{BrowserQRCodeReader}from'@zxing/browser';
import'./styles.css';

const auth=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'');
const NAV=[['overview','Overview'],['prereg','Pre-Registration'],['events','Event Registration'],['profiles','Profiles'],['abstracts','Abstracts'],['brochure','Brochure'],['contact','Contact'],['gmail','QR Gmail'],['scanner','QR Scanner'],['admins','Admin Management']];

async function call(action,payload={}){
 const {data:{session}}=await auth.auth.getSession();
 if(!session)throw new Error('Your secure session has expired. Please sign in again.');
 const r=await fetch('/.netlify/functions/admin-api',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({action,...payload})});
 const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'Admin request failed');return j;
}
async function authorize(s){const {data,error}=await auth.auth.getUser(s.access_token);if(error||!data.user)throw new Error('Invalid session');const r=await call('admins');const a=(r.data||[]).find(x=>x.email.toLowerCase()===data.user.email.toLowerCase());if(!a||!a.enabled)throw new Error('Your account is not enabled for this admin portal.');return a}

function App(){const[s,setS]=useState(null),[admin,setAdmin]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let live=true;auth.auth.getSession().then(async x=>{if(!live)return;if(!x.data.session){setBusy(false);return}try{setAdmin(await authorize(x.data.session));setS(x.data.session)}catch(e){setError(e.message);await auth.auth.signOut()}finally{setBusy(false)}});const sub=auth.auth.onAuthStateChange(async(_,x)=>{if(!live)return;if(!x){setS(null);setAdmin(null);setBusy(false);return}try{setAdmin(await authorize(x));setS(x);setError('')}catch(e){setError(e.message);await auth.auth.signOut()}finally{setBusy(false)}});return()=>{live=false;sub.data.subscription.unsubscribe()}},[]);
 if(busy)return <div className="screen"><Spin/>Checking secure access…</div>;
 if(!s||!admin)return <Login error={error}/>;
 return <Console admin={admin} logout={()=>auth.auth.signOut()}/>
}

function Login({error}){const[email,setEmail]=useState(''),[pass,setPass]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(error||'');
 async function go(e){e.preventDefault();setBusy(true);setMsg('');const r=await auth.auth.signInWithPassword({email,password:pass});if(r.error)setMsg(r.error.message);setBusy(false)}
 return <div className="auth"><div className="auth-card"><div className="logo">EXCELSIOR<span>'26</span></div><small className="kicker">SECURE ADMIN CONTROL</small><h1>Welcome back.</h1><p>Authorized administrators only.</p><form onSubmit={go}><Field label="Gmail"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></Field><Field label="Password"><input type="password" value={pass} onChange={e=>setPass(e.target.value)} required autoComplete="current-password"/></Field>{msg&&<Alert text={msg}/>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in securely'}</button></form><div className="security">Supabase Auth • admin authorization • server-protected writes</div></div></div>
}

function Console({admin,logout}){const[page,setPage]=useState('overview');return <div className="app"><aside><div className="brand">EXCELSIOR<span>'26</span><small>ADMIN CONSOLE</small></div><nav>{NAV.map(x=><button className={page===x[0]?'active':''} onClick={()=>setPage(x[0])} key={x[0]}><b>{x[0].slice(0,1).toUpperCase()}</b>{x[1]}</button>)}</nav><div className="user"><strong>{admin.display_name||'Administrator'}</strong><small>{admin.email}</small><em>AUTHORIZED ADMIN</em><button onClick={logout}>Sign out</button></div></aside><main><header><div><small className="kicker">EXCELSIOR'26 / CONTROL CENTER</small><h2>{NAV.find(x=>x[0]===page)[1]}</h2></div><span className="online">● Secure session</span></header><div className="content"><Page page={page} admin={admin}/></div></main><div className="bottom">{NAV.slice(0,5).map(x=><button className={page===x[0]?'active':''} onClick={()=>setPage(x[0])} key={x[0]}>{x[1].split(' ')[0]}</button>)}</div></div>}

function Page({page,admin}){if(page==='overview')return <Overview/>;if(page==='prereg')return <Review title="Pre-Registration Review" action="master_review" fields={['master_id','full_name','email','phone','year','pre_payment_status','pre_utr','pre_registration_status','pre_approved_by','pre_approved_at']}/>;if(page==='events')return <Events/>;if(page==='profiles')return <Profiles/>;if(page==='abstracts')return <Abstracts/>;if(page==='brochure')return <Brochure/>;if(page==='contact')return <Contact/>;if(page==='gmail')return <Gmail/>;if(page==='scanner')return <Scanner/>;return <Admins admin={admin}/>}
function Overview(){const[d,setD]=useState(null),[e,setE]=useState('');
 useEffect(()=>{call('overview').then(setD).catch(x=>setE(x.message))},[]);
 if(e)return <Panel title="Overview"><Alert text={e}/></Panel>;
 const c=d?.counts||['—','—','—','—'];return <><div className="hero"><div><small className="kicker">COMMAND OVERVIEW</small><h1>Good to see you.</h1><p>Monitor registrations, payments, abstracts, event activity and participant communication from one secure workspace.</p></div><div className="hero-logo">E<span>'26</span></div></div><div className="stats">{[['Pre-registrations',c[0]],['Event registrations',c[1]],['Abstract submissions',c[2]],['QR verifications',c[3]]].map(x=><div className="stat" key={x[0]}><small>LIVE</small><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="cols"><Panel title="Operations"><Action title="Registration review" text="Approve or reject master registrations and event payments."/><Action title="Abstract desk" text="Review submissions with clear status and reviewer metadata."/><Action title="QR communication" text="Prepare, approve and send participant QR emails securely."/></Panel><Panel title="Security"><Row a="Authentication" b="Supabase Auth"/><Row a="Authorization" b="admin_accounts"/><Row a="Privileged writes" b="Netlify Functions"/><Row a="Service credentials" b="Server only"/></Panel></div></>
}

function Review({title,action,fields}){const[d,setD]=useState(null),[q,setQ]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');useEffect(()=>{call(action==='master_review'?'master_list':'event_list').then(x=>setD(x.data||[])).catch(x=>setError(x.message))},[action]);const list=useMemo(()=>{const a=d||[];return a.filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()))},[d,q]);async function act(id,status){setBusy(id+status);setError('');try{await call(action,{id,status});const x=await call(action==='master_review'?'master_list':'event_list');setD(x.data||[])}catch(e){setError(e.message)}finally{setBusy('')}}return <Panel title={title} extra={<span className="pill">{list.length} records</span>}>{error&&<Alert text={error}/>}<div className="toolbar"><input placeholder="Search records…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{fields.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{fields.map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td><button className="mini good" disabled={!!busy} onClick={()=>act(r.id,'approved')}>{busy===r.id+'approved'?'…':'Approve'}</button><button className="mini bad" disabled={!!busy} onClick={()=>act(r.id,'rejected')}>{busy===r.id+'rejected'?'…':'Reject'}</button></td></tr>)}</tbody></table></div>}</Panel>
}

function Events(){const[d,setD]=useState(null),[cfg,setCfg]=useState(null),[tab,setTab]=useState('registrations'),[q,setQ]=useState('');useEffect(()=>{Promise.all([call('event_list'),call('event_config')]).then(x=>{setD(x[0].data||[]);setCfg(x[1].data||[])}).catch(()=>{})},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <><Panel title="Event Registration" extra={<div className="tabs"><button className={tab==='registrations'?'sel':''} onClick={()=>setTab('registrations')}>Registrations</button><button className={tab==='config'?'sel':''} onClick={()=>setTab('config')}>Event configuration</button></div>}>{tab==='registrations'?<><div className="toolbar"><input placeholder="Search participant, event, UTR…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{['master_id','name','event','fee','utr','payment_status','status','team_id','event_code'].map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{list.map(r=><EventRow key={r.id} r={r} reload={()=>call('event_list').then(x=>setD(x.data||[]))}/>)}</tbody></table></div>}</>:<Config rows={cfg} setRows={setCfg}/>}</Panel></>
}
function EventRow({r,reload}){const[b,setB]=useState(false);async function act(kind,status){setB(true);try{await call(kind,{id:r.id,status});await reload()}catch(e){alert(e.message)}finally{setB(false)}}return <tr>{['master_id','name','event','fee','utr','payment_status','status','team_id','event_code'].map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td><button className="mini good" disabled={b} onClick={()=>act('payment_review','approved')}>Pay ✓</button><button className="mini good" disabled={b} onClick={()=>act('event_review','approved')}>Approve</button><button className="mini bad" disabled={b} onClick={()=>act('event_review','rejected')}>Reject</button></td></tr>}
function Config({rows,setRows}){return <div className="config-grid">{rows.map(x=><div className="config-card" key={x.key}><div className="editor-title"><b>{x.title}</b><span className="pill">{x.enabled?'Enabled':'Disabled'}</span></div><Field label="Title"><input value={x.title||''} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,title:e.target.value}:y))}/></Field><div className="two"><Field label="Fee"><input type="number" value={x.fee||0} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,fee:e.target.value}:y))}/></Field><Field label="Enabled"><select value={String(x.enabled)} onChange={e=>setRows(rows.map(y=>y.key===x.key?{...y,enabled:e.target.value==='true'}:y))}><option value="true">Enabled</option><option value="false">Disabled</option></select></Field></div><button className="primary" onClick={async()=>{try{await call('event_config_update',x);alert('Event configuration saved.')}catch(e){alert(e.message)}}}>Save configuration</button></div>)}</div>}
function Profiles(){const[d,setD]=useState(null),[q,setQ]=useState('');useEffect(()=>{call('profiles').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <Panel title="Participant Profiles"><div className="toolbar"><input placeholder="Search master ID, name, email or phone…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<Table rows={list} fields={['master_id','full_name','email','phone','year','pre_payment_status','pre_registration_status','created_at']}/>}</Panel>}
function Abstracts(){const[d,setD]=useState(null),[q,setQ]=useState('');useEffect(()=>{call('abstract_list').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const list=(d||[]).filter(x=>!q||Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));async function review(id,status){try{await call('abstract_review',{id,status});setD((await call('abstract_list')).data||[])}catch(e){alert(e.message)}}return <Panel title="Abstract Review"><div className="toolbar"><input placeholder="Search title, master ID or event…" value={q} onChange={e=>setQ(e.target.value)}/></div>{!d?<Loading/>:<div className="table"><table><thead><tr>{['master_id','event_title','title','status','submitted_at','file_name'].map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}<th>Review</th></tr></thead><tbody>{list.map(r=><tr key={r.id}>{['master_id','event_title','title','status','submitted_at','file_name'].map(x=><td key={x}>{String(r[x]??'—')}</td>)}<td><button className="mini good" onClick={()=>review(r.id,'approved')}>Approve</button><button className="mini bad" onClick={()=>review(r.id,'rejected')}>Reject</button><button className="mini" onClick={()=>review(r.id,'resubmission_required')}>Resubmit</button></td></tr>)}</tbody></table></div>}</Panel>}
function Brochure(){const[file,setFile]=useState(null),[busy,setBusy]=useState(false);return <Panel title="Brochure"><div className="info">Existing bucket: <b>excelsior-brochure</b>. It is public, PDF-only, with a 50 MB limit. Replacement is server-controlled.</div><Field label="Replace brochure PDF"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><button className="primary" disabled={!file||busy} onClick={async()=>{setBusy(true);try{const reader=new FileReader();reader.onload=async()=>{try{await call('brochure_upload',{name:file.name,data_url:String(reader.result)});alert('Brochure replaced successfully.')}catch(e){alert(e.message)}finally{setBusy(false)}};reader.readAsDataURL(file)}catch(e){setBusy(false);alert(e.message)}}}>{busy?'Uploading…':'Upload replacement'}</button></Panel>}
function Contact(){const[d,setD]=useState(null);useEffect(()=>{call('site_content').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);if(!d)return <Panel title="Contact / Shared Site Content"><Loading/></Panel>;return <Panel title="Contact / Shared Site Content"><div className="info">This edits the shared <b>site_content</b> source used by the participant portal. No duplicate content store is created.</div>{d.map(x=><div className="editor" key={x.key}><div className="editor-title"><b>{x.title||x.key}</b><span className="pill">{x.enabled?'Published':'Disabled'}</span></div><Field label="Title"><input value={x.title} onChange={e=>setD(d.map(y=>y.key===x.key?{...y,title:e.target.value}:y))}/></Field><Field label="Content"><textarea rows="6" value={x.content} onChange={e=>setD(d.map(y=>y.key===x.key?{...y,content:e.target.value}:y))}/></Field><button className="primary" onClick={async()=>{try{await call('content_update',x);alert('Saved successfully.')}catch(e){alert(e.message)}}}>Save changes</button></div>)}</Panel>}
function Gmail(){const[d,setD]=useState(null),[sel,setSel]=useState([]),[subject,setSubject]=useState("EXCELSIOR'26 Registration QR"),[body,setBody]=useState("Hello {{name}}, your EXCELSIOR'26 registration QR is ready. Master ID: {{master_id}}."),[busy,setBusy]=useState(false),[qr,setQr]=useState('');useEffect(()=>{call('profiles').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);const all=d&&d.length>0&&d.every(x=>sel.includes(x.id));const toggle=id=>setSel(s=>s.includes(id)?s.filter(x=>x!==id):s.concat(id));async function preview(){const x=(d||[]).find(y=>sel.includes(y.id));if(!x)return;const z=await call('qr_prepare',{master_ids:[x.id]});const item=z.data?.[0];if(item)setQr(await QRCode.toDataURL(JSON.stringify({master_id:item.master_id,token:item.qr.token}),{width:260}))}async function send(){setBusy(true);try{const z=await call('qr_prepare',{master_ids:sel});const recipients=(z.data||[]).map(x=>({master_id:x.master_id,email:x.email,qr_credential_id:x.qr.id}));const queued=await call('qr_queue',{recipients,subject,body_html:body});const sent=await fetch('/.netlify/functions/send-qr-email',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(await auth.auth.getSession()).data.session.access_token},body:JSON.stringify({queue_ids:(queued.data||[]).map(x=>x.id)})});const sj=await sent.json();if(!sent.ok||!sj.ok)throw new Error(sj.error||'Send failed');alert('QR email processing complete.');setSel([])}catch(e){alert(e.message)}finally{setBusy(false)}}return <><Panel title="QR Gmail" extra={<span className="pill blue">{sel.length} selected</span>}><div className="info">Select recipients, edit the template, preview a QR, then send through the protected server. Credentials never enter browser code.</div><div className="toolbar"><button onClick={()=>setSel(all?[]:(d||[]).map(x=>x.id))}>{all?'Unselect All':'Select All'}</button><button onClick={()=>setSel([])}>Clear All</button></div>{!d?<Loading/>:<div className="recipients">{d.map(x=><label key={x.id}><input type="checkbox" checked={sel.includes(x.id)} onChange={()=>toggle(x.id)}/><span><b>{x.full_name}</b><small>{x.email} • {x.master_id}</small></span></label>)}</div>}</Panel><div className="cols"><Panel title="Email template"><Field label="Subject"><input value={subject} onChange={e=>setSubject(e.target.value)}/></Field><Field label="Body"><textarea rows="9" value={body} onChange={e=>setBody(e.target.value)}/></Field><small className="muted">Placeholders: {{name}}, {{master_id}}, {{email}}</small><div className="buttons"><button onClick={preview} disabled={!sel.length}>Preview QR</button><button className="primary" onClick={send} disabled={!sel.length||busy}>{busy?'Sending…':'Send selected'}</button></div></Panel><Panel title="QR preview">{qr?<img className="qr" src={qr}/>:<div className="preview">Select a participant and preview their QR.</div>}</Panel></div></>}
function Scanner(){const[t,setT]=useState(''),[r,setR]=useState(null),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),video=React.useRef(null),reader=React.useRef(null);useEffect(()=>()=>{try{reader.current?.reset()}catch{}},[]);async function validate(token=t){setBusy(true);try{setR(await call('qr_validate',{token}))}catch(e){setR({error:e.message})}finally{setBusy(false)}}async function start(){try{reader.current=new BrowserQRCodeReader();setRunning(true);await reader.current.decodeFromVideoDevice(undefined,video.current,async result=>{if(result){const text=result.getText();setT(text);await validate(text);reader.current?.reset();setRunning(false)}})}catch(e){setR({error:'Camera unavailable. Use manual token entry or allow camera access.'});setRunning(false)}}return <Panel title="QR Scanner"><div className="scanner live"><video ref={video} muted playsInline/><div className="scan-overlay">ALIGN QR INSIDE FRAME</div></div><div className="buttons"><button onClick={start} disabled={running}>{running?'Scanning…':'Start camera'}</button><button onClick={()=>{reader.current?.reset();setRunning(false)}}>Stop</button></div><Field label="Manual token"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Paste QR token"/></Field><button className="primary" disabled={!t||busy} onClick={()=>validate()}>{busy?'Validating…':'Validate token'}</button>{r&&<div className={'scan-result '+(r.result||'invalid')}><b>{r.result||'error'}</b><span>{r.reason||r.error}</span>{r.master_id&&<small>Master ID: {r.master_id}</small>}</div>}</Panel>}
function Admins({admin}){const[d,setD]=useState(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{call('admins').then(x=>setD(x.data||[])).catch(()=>setD([]))},[]);if(admin.role!=='owner')return <Panel title="Admin Management"><Alert text="Owner authorization is required for this area."/></Panel>;async function add(){setBusy(true);try{await call('admin_create',{email,display_name:name});alert('Invitation sent and admin account created.');setName('');setEmail('');setD((await call('admins')).data||[])}catch(e){alert(e.message)}finally{setBusy(false)}}return <Panel title="Admin Management"><div className="info">Owner-only. Maximum 10 enabled admins. New administrators receive a Supabase invitation and set their own password; this portal never handles plaintext passwords.</div><div className="form-row"><Field label="Display name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Gmail"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><button className="primary" disabled={!name||!email||busy} onClick={add}>{busy?'Inviting…':'Invite admin'}</button></div>{!d?<Loading/>:<Table rows={d} fields={['display_name','email','enabled','created_at']}/>}</Panel>}
function Table({rows,fields}){if(!rows?.length)return <div className="empty">No records found.</div>;const c=fields||Object.keys(rows[0]).slice(0,8);return <div className="table"><table><thead><tr>{c.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{c.map(x=><td key={x}>{String(r[x]??'—')}</td>)}</tr>)}</tbody></table></div>}
const Action=p=><div className="action"><b>{p.title}</b><span>{p.text}</span><i>→</i></div>;const Row=p=><div className="row"><b>{p.a}</b><span className="pill green">{p.b}</span></div>;const Panel=p=><section className="panel"><div className="panel-head"><h3>{p.title}</h3>{p.extra}</div>{p.children}</section>;const Field=p=><label className="field"><small>{p.label}</small>{p.children}</label>;const Alert=p=><div className="alert">{p.text}</div>;const Spin=()=> <div className="spin"/>;const Loading=()=> <div className="loading"><Spin/>Loading…</div>;
createRoot(document.getElementById('root')).render(<App/>);